In [ ]:
import pandas as pd

# Esta es la URL correcta para descargar SOLO los datos
url = 'https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/Startups%20in%202021%20end.csv'

# Cambiamos el sep=";" por sep="," porque es un CSV estándar
startups = pd.read_csv(url,
                       encoding='ISO-8859-1',
                       on_bad_lines="skip",
                       sep=",")

# Verificamos que cargó bien
startups.head()

,Unnamed: 0,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [ ]:
startups.dtypes

company_id            int64
Company              object
Valuation ($B)      float64
Date Joined          object
Country              object
City                 object
Industry             object
Select Investors     object
dtype: object

In [ ]:
#cambiamos por numero flotante para poder sumar
startups['Valuation ($B)'] = startups['Valuation ($B)'].str.replace('$', '').str.replace('B', '', regex=False)
startups['Valuation ($B)'] = pd.to_numeric(startups['Valuation ($B)'], errors='coerce')

In [ ]:
startups.head() #obervamos que se haya creado correctamente

,company_id,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,140.0,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,Stripe,95.0,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,3,Klarna,45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,4,Canva,40.0,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [ ]:
#cambiamos el nombre de la columna unnamed para no generar confusion
startups.rename(columns={'Unnamed: 0': 'company_id'}, inplace=True)

In [ ]:
startups.head()

,company_id,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,$140,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,$100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,Stripe,$95,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,3,Klarna,$45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,4,Canva,$40,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [ ]:
startups.dtypes

company_id            int64
Company              object
Valuation ($B)      float64
Date Joined          object
Country              object
City                 object
Industry             object
Select Investors     object
dtype: object

In [ ]:
startups.head()

,company_id,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,140.0,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,1,SpaceX,100.3,12/1/2012,United States,Hawthorne,Other,"Founders Fund, Draper Fisher Jurvetson, Rothen..."
2,2,Stripe,95.0,1/23/2014,United States,San Francisco,Fintech,"Khosla Ventures, LowercaseCapital, capitalG"
3,3,Klarna,45.6,12/12/2011,Sweden,Stockholm,Fintech,"Institutional Venture Partners, Sequoia Capita..."
4,4,Canva,40.0,1/8/2018,Australia,Surry Hills,Internet software & services,"Sequoia Capital China, Blackbird Ventures, Mat..."

In [ ]:
#Indicadores y metricas clave del data set

#Empresas de IA en China
mask=startups['Industry']=='Artificial intelligence'
mask2=startups['Country']=='China'
startups[mask & mask2].reset_index(drop=True)

,company_id,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,140.00,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."
1,26,SenseTime,12.00,7/11/2017,China,Shanghai,Artificial intelligence,"Star VC, IDG Capital, Infore Capital, Alibaba ..."
2,118,Horizon Robotics,5.00,2/27/2019,China,Beijing,Artificial intelligence,"Hillhouse Capital Management, Linear Venture, ..."
3,155,MEGVII,4.00,10/31/2017,China,Beijing,Artificial intelligence,"Ant Financial Services Group, Russia-China Inv..."
4,204,Cloudwalk,3.32,10/8/2018,China,Guangzhou,Artificial intelligence,"Oriza Holdings, Guangdong Technology Financial..."
5,334,YITU Technology,2.17,3/8/2018,China,Shanghai,Artificial intelligence,"Sequoia Capital China, Banyan Capital"
6,359,4Paradigm,2.00,12/19/2018,China,Beijing,Artificial intelligence,"Sequoia Capital China, China Construction Bank..."
7,390,XtalPi,2.00,8/11/2021,China,Shenzhen,Artificial intelligence,"Tencent Holdings, 5Y Capital, Sequoia Capital ..."
8,398,Black Sesame Technologies,2.00,9/22/2021,China,Shanghai,Artificial intelligence,"Northern Light Venture Capital, Xiaomi, Future..."
9,558,DeepBlue Technology,1.35,4/16/2018,China,Shanghai,Artificial intelligence,"DESUN Capital, Yunfeng Capital, Meridian Capital"
10,618,Aibee,1.20,4/13/2021,China,Beijing,Artificial intelligence,"Sequoia Capital China, Lenovo Capital and Incu..."
11,643,Unisound,1.19,7/19/2018,China,Beijing,Artificial intelligence,"Qiming Venture Partners, China Internet Invest..."
12,644,Mininglamp Technology,1.19,3/27/2019,China,Beijing,Artificial intelligence,"Russia-China Investment Fund, Tencent Holdings..."
13,698,Hesai Tech,1.05,8/1/2020,China,Shanghai,Artificial intelligence,"Lightspeed China Partners, Baidu Ventures, Qim..."
14,724,iCarbonX,1.00,4/12/2016,China,Shenzhen,Artificial intelligence,"Tencent, Vcanbio"
15,753,Momenta,1.00,10/17/2018,China,Beijing,Artificial intelligence,"Sinovation Ventures, Tencent Holdings, Sequoia..."
16,763,Intellifusion,1.00,3/22/2019,China,Shenzhen,Artificial intelligence,"BOC International, TopoScend Capital, Hongxiu VC"
17,791,AInnovation,1.00,12/16/2020,China,Beijing,Artificial intelligence,"CICC ALPHA, Chengwei Capital, Sinovation Ventures"

In [ ]:
#Empresa con mayor valuacion
max_valuation = startups['Valuation ($B)'].max()
company_with_max_valuation = startups[startups['Valuation ($B)'] == max_valuation]
display(company_with_max_valuation)

,company_id,Company,Valuation ($B),Date Joined,Country,City,Industry,Select Investors
0,0,Bytedance,140.0,4/7/2017,China,Beijing,Artificial intelligence,"Sequoia Capital China, SIG Asia Investments, S..."

In [ ]:
# Numero total de paises unicos
total_countries = startups['Country'].nunique()
print(f"Numero total de paises: {total_countries}")

Numero total de paises: 47

In [ ]:
# Empresas por pais
companies_per_country = startups['Country'].value_counts()
display(companies_per_country)

Country
United States           477
China                   169
India                    51
United Kingdom           37
Germany                  23
Israel                   21
France                   19
Brazil                   15
Canada                   15
South Korea              11
Singapore                11
Hong Kong                 7
Japan                     6
Australia                 6
Netherlands               5
Mexico                    5
Switzerland               4
Sweden                    4
Indonesia                 4
Spain                     4
Norway                    3
Ireland                   3
United Arab Emirates      3
Turkey                    2
Colombia                  2
Belgium                   2
Austria                   2
Finland                   2
Denmark                   2
Philippines               2
Thailand                  2
South Africa              2
Luxembourg                1
Vietnam                   1
Estonia                   1
Lithuania                 1
Argentina                 1
Nigeria                   1
Santa Clara               1
Bermuda                   1
Senegal                   1
Chile                     1
Malaysia                  1
Czech Republic            1
Croatia                   1
United States,            1
Indonesia,                1
Name: count, dtype: int64

In [ ]:
# Numero total de industrias unicas
total_industries = startups['Industry'].nunique()
print(f"Numero total de industrias: {total_industries}")

Numero total de industrias: 17

In [ ]:
# Empresas por industria
companies_per_industry = startups['Industry'].value_counts()
display(companies_per_industry)

Industry
Fintech                                190
Internet software & services           167
E-commerce & direct-to-consumer        102
Artificial intelligence                 69
Health                                  63
Supply chain, logistics, & delivery     51
Other                                   51
Cybersecurity                           41
Mobile & telecommunications             37
Data management & analytics             36
Hardware                                32
Auto & transportation                   29
Edtech                                  27
Consumer & retail                       23
Travel                                  13
Artificial Intelligence                  4
Finttech                                 1
Name: count, dtype: int64

In [ ]:
# Guardar el DataFrame 'startups' en un archivo CSV
startups.to_csv('startups.csv', index=False)
print("DataFrame 'startups' guardado como 'startups.csv'")

DataFrame 'startups' guardado como 'startups.csv'